//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dualog.eCatch.Shared.Language {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dualog.eCatch.Shared.Language.Translations", typeof(Translations).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air draught.
        /// </summary>
        public static string AirDraught {
            get {
                return ResourceManager.GetString("AirDraught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival.
        /// </summary>
        public static string Arrival {
            get {
                return ResourceManager.GetString("Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival at.
        /// </summary>
        public static string ArrivalAt {
            get {
                return ResourceManager.GetString("ArrivalAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arriving at position.
        /// </summary>
        public static string ArrivingAtPosition {
            get {
                return ResourceManager.GetString("ArrivingAtPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch.
        /// </summary>
        public static string Catch {
            get {
                return ResourceManager.GetString("Catch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch area.
        /// </summary>
        public static string CatchArea {
            get {
                return ResourceManager.GetString("CatchArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch report.
        /// </summary>
        public static string CatchReport {
            get {
                return ResourceManager.GetString("CatchReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control point.
        /// </summary>
        public static string ControlPoint {
            get {
                return ResourceManager.GetString("ControlPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for control.
        /// </summary>
        public static string ControlTime {
            get {
                return ResourceManager.GetString("ControlTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrected.
        /// </summary>
        public static string Corrected {
            get {
                return ResourceManager.GetString("Corrected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily catch.
        /// </summary>
        public static string DailyCatch {
            get {
                return ResourceManager.GetString("DailyCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/time.
        /// </summary>
        public static string DateAndTime {
            get {
                return ResourceManager.GetString("DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivering.
        /// </summary>
        public static string Delivering {
            get {
                return ResourceManager.GetString("Delivering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivering to.
        /// </summary>
        public static string DeliveringTo {
            get {
                return ResourceManager.GetString("DeliveringTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery date.
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery harbour.
        /// </summary>
        public static string DeliveryHarbour {
            get {
                return ResourceManager.GetString("DeliveryHarbour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery method.
        /// </summary>
        public static string DeliveryMethod {
            get {
                return ResourceManager.GetString("DeliveryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery time.
        /// </summary>
        public static string DeliveryTime {
            get {
                return ResourceManager.GetString("DeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        public static string Departure {
            get {
                return ResourceManager.GetString("Departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure from.
        /// </summary>
        public static string DepartureFrom {
            get {
                return ResourceManager.GetString("DepartureFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose name for device and approve it.
        /// </summary>
        public static string DeviceApproveAndGiveName {
            get {
                return ResourceManager.GetString("DeviceApproveAndGiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributed over.
        /// </summary>
        public static string DistributedOver {
            get {
                return ResourceManager.GetString("DistributedOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End position.
        /// </summary>
        public static string EndPosition {
            get {
                return ResourceManager.GetString("EndPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering zone.
        /// </summary>
        public static string EnteringZone {
            get {
                return ResourceManager.GetString("EnteringZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated catch value.
        /// </summary>
        public static string EstimatedCatchValue {
            get {
                return ResourceManager.GetString("EstimatedCatchValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated weight at departure.
        /// </summary>
        public static string EstimatedWeightAtDeparture {
            get {
                return ResourceManager.GetString("EstimatedWeightAtDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting zone.
        /// </summary>
        public static string ExitingZone {
            get {
                return ResourceManager.GetString("ExitingZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faroe Islands.
        /// </summary>
        public static string FaroeIslands {
            get {
                return ResourceManager.GetString("FaroeIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing activity.
        /// </summary>
        public static string FishingActivity {
            get {
                return ResourceManager.GetString("FishingActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing days.
        /// </summary>
        public static string FishingDays {
            get {
                return ResourceManager.GetString("FishingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish on board.
        /// </summary>
        public static string FishOnBoard {
            get {
                return ResourceManager.GetString("FishOnBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price list for fish.
        /// </summary>
        public static string FishPriceList {
            get {
                return ResourceManager.GetString("FishPriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish species.
        /// </summary>
        public static string FishSpecies {
            get {
                return ResourceManager.GetString("FishSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish start.
        /// </summary>
        public static string FishStart {
            get {
                return ResourceManager.GetString("FishStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarded to.
        /// </summary>
        public static string ForwardedTo {
            get {
                return ResourceManager.GetString("ForwardedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear.
        /// </summary>
        public static string Gear {
            get {
                return ResourceManager.GetString("Gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear details.
        /// </summary>
        public static string GearDetails {
            get {
                return ResourceManager.GetString("GearDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harbour.
        /// </summary>
        public static string Harbour {
            get {
                return ResourceManager.GetString("Harbour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haul.
        /// </summary>
        public static string Haul {
            get {
                return ResourceManager.GetString("Haul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haul duration.
        /// </summary>
        public static string HaulDuration {
            get {
                return ResourceManager.GetString("HaulDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haul ended.
        /// </summary>
        public static string HaulEnded {
            get {
                return ResourceManager.GetString("HaulEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haul report.
        /// </summary>
        public static string HaulReport {
            get {
                return ResourceManager.GetString("HaulReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour of the day.
        /// </summary>
        public static string HourOfDay {
            get {
                return ResourceManager.GetString("HourOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediately.
        /// </summary>
        public static string Immediately {
            get {
                return ResourceManager.GetString("Immediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        public static string Is {
            get {
                return ResourceManager.GetString("Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landed.
        /// </summary>
        public static string Landed {
            get {
                return ResourceManager.GetString("Landed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message log.
        /// </summary>
        public static string MessageLog {
            get {
                return ResourceManager.GetString("MessageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type.
        /// </summary>
        public static string MessageType {
            get {
                return ResourceManager.GetString("MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net weight.
        /// </summary>
        public static string NetWeight {
            get {
                return ResourceManager.GetString("NetWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway.
        /// </summary>
        public static string Norway {
            get {
                return ResourceManager.GetString("Norway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On board.
        /// </summary>
        public static string Onboard {
            get {
                return ResourceManager.GetString("Onboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other fish species.
        /// </summary>
        public static string OtherSpecies {
            get {
                return ResourceManager.GetString("OtherSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned activity.
        /// </summary>
        public static string PlannedActivity {
            get {
                return ResourceManager.GetString("PlannedActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned activity is.
        /// </summary>
        public static string PlannedActivityIs {
            get {
                return ResourceManager.GetString("PlannedActivityIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string PostCity {
            get {
                return ResourceManager.GetString("PostCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per kilo.
        /// </summary>
        public static string PricePerKilo {
            get {
                return ResourceManager.GetString("PricePerKilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio call signal.
        /// </summary>
        public static string RadioCallSignal {
            get {
                return ResourceManager.GetString("RadioCallSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record number.
        /// </summary>
        public static string RecordNumber {
            get {
                return ResourceManager.GetString("RecordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reported.
        /// </summary>
        public static string Reported {
            get {
                return ResourceManager.GetString("Reported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return messages in plain text.
        /// </summary>
        public static string ReturnMessagesInPlainText {
            get {
                return ResourceManager.GetString("ReturnMessagesInPlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        public static string Russia {
            get {
                return ResourceManager.GetString("Russia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship name.
        /// </summary>
        public static string ShipName {
            get {
                return ResourceManager.GetString("ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show error log.
        /// </summary>
        public static string ShowErrorLog {
            get {
                return ResourceManager.GetString("ShowErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in table.
        /// </summary>
        public static string ShowInTable {
            get {
                return ResourceManager.GetString("ShowInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipper.
        /// </summary>
        public static string Skipper {
            get {
                return ResourceManager.GetString("Skipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skippers name.
        /// </summary>
        public static string SkippersName {
            get {
                return ResourceManager.GetString("SkippersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start position.
        /// </summary>
        public static string StartPosition {
            get {
                return ResourceManager.GetString("StartPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address.
        /// </summary>
        public static string StreetAddress {
            get {
                return ResourceManager.GetString("StreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target species.
        /// </summary>
        public static string TargetSpecies {
            get {
                return ResourceManager.GetString("TargetSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This.
        /// </summary>
        public static string This {
            get {
                return ResourceManager.GetString("This", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool type.
        /// </summary>
        public static string ToolType {
            get {
                return ResourceManager.GetString("ToolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total weight.
        /// </summary>
        public static string TotalWeight {
            get {
                return ResourceManager.GetString("TotalWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfered fish.
        /// </summary>
        public static string TransferedFish {
            get {
                return ResourceManager.GetString("TransferedFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfered from.
        /// </summary>
        public static string TransferedFrom {
            get {
                return ResourceManager.GetString("TransferedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfered to.
        /// </summary>
        public static string TransferedTo {
            get {
                return ResourceManager.GetString("TransferedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transferred at position.
        /// </summary>
        public static string TransferredAtPosition {
            get {
                return ResourceManager.GetString("TransferredAtPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transshipment.
        /// </summary>
        public static string Transshipment {
            get {
                return ResourceManager.GetString("Transshipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel.
        /// </summary>
        public static string Vessel {
            get {
                return ResourceManager.GetString("Vessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight at departure is.
        /// </summary>
        public static string WeightAtDepartureIs {
            get {
                return ResourceManager.GetString("WeightAtDepartureIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight on board.
        /// </summary>
        public static string WeightOnBoard {
            get {
                return ResourceManager.GetString("WeightOnBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight on board all ships.
        /// </summary>
        public static string WeightOnBoardAllShips {
            get {
                return ResourceManager.GetString("WeightOnBoardAllShips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        public static string When {
            get {
                return ResourceManager.GetString("When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterdays catch.
        /// </summary>
        public static string YesterdaysCatch {
            get {
                return ResourceManager.GetString("YesterdaysCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string Zone {
            get {
                return ResourceManager.GetString("Zone", resourceCulture);
            }
        }
    }
}
